version: "3.8"

services:
  flateos:
    image: "archlinux:latest"
    container_name: "flateos"
    restart: always
    working_dir: $PWD
    entrypoint: ["./bootstrap.sh"]
    networks:
      - flateos-net
    privileged: true
    tty: true
    volumes:
      - .:/$PWD
    env_file: .env

networks:
  flateos-net:
    driver: bridge
