version: "3.8"

services:
  flateos:
    image: "archlinux:latest"
    restart: unless-stopped
    working_dir: "/src"
    entrypoint: "./bootstrap.sh"
    networks:
      - flateos-net
    privileged: true
    tty: true

networks:
  flateos-net:
    driver: bridge
